# Generated by Django 5.0.2 on 2024-02-29 07:01

import demo_api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', demo_api.models.CustomUserManager()),
            ],
        ),
    ]
